// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationAssignmentWeb.Data;

#nullable disable

namespace RegistrationAssignmentWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220601041429_createdb")]
    partial class createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RegistrationAssignmentWeb.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("RegistrationAssignmentWeb.Model.RegisterUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalRequest")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("InterestArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegisterUser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalRequest = "request1",
                            Email = "test1@gmail.com",
                            Gender = "M",
                            InterestArea = 160,
                            Name = "test1",
                            RegisterDate = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AdditionalRequest = "request2",
                            Email = "test2@gmail.com",
                            Gender = "F",
                            InterestArea = 37,
                            Name = "test2",
                            RegisterDate = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AdditionalRequest = "request3",
                            Email = "test3@gmail.com",
                            Gender = "F",
                            InterestArea = 37,
                            Name = "test3",
                            RegisterDate = new DateTime(2023, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RegistrationAssignmentWeb.Model.RegisterUserEventDays", b =>
                {
                    b.Property<int>("RegisterUserEventDaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterUserEventDaysId"), 1L, 1);

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterUserId")
                        .HasColumnType("int");

                    b.HasKey("RegisterUserEventDaysId");

                    b.HasIndex("RegisterUserId");

                    b.ToTable("RegisterUserEventDays");

                    b.HasData(
                        new
                        {
                            RegisterUserEventDaysId = 1,
                            Days = "Day 1",
                            RegisterUserId = 1
                        },
                        new
                        {
                            RegisterUserEventDaysId = 2,
                            Days = "Day 1",
                            RegisterUserId = 2
                        },
                        new
                        {
                            RegisterUserEventDaysId = 3,
                            Days = "Day 1",
                            RegisterUserId = 3
                        });
                });

            modelBuilder.Entity("RegistrationAssignmentWeb.Model.RegisterUserEventDays", b =>
                {
                    b.HasOne("RegistrationAssignmentWeb.Model.RegisterUser", "RegisterUser")
                        .WithMany("RegisterUserEveDays")
                        .HasForeignKey("RegisterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisterUser");
                });

            modelBuilder.Entity("RegistrationAssignmentWeb.Model.RegisterUser", b =>
                {
                    b.Navigation("RegisterUserEveDays");
                });
#pragma warning restore 612, 618
        }
    }
}
